backend:
  name: [github | gitlab]
  repo: ldchinhcr/GithubIssueListClone   # Path to your Github/Gitlab repository
  branch: chinh    # Branch to update
  base_url: https://api.netlify.com/ # Path to ext auth provider